version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ecommNestDB
    environment:
      POSTGRES_USER: ecomm_admin
      POSTGRES_PASSWORD:
      POSTGRES_DB: ecomm
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
